spring:
  application:
    name: security-demo
  datasource:
    url: jdbc:mysql://192.168.0.4:3306/tm_animal?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    username: root
    password: zhaoxuniubi
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  redis:
    host: localhost
    port: 6379
    database: 4
server:
  port: 8015
mybatis:
  mapper-locations: classpath:mapping/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
